// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: provider/v1alpha1/public.proto

package providerv1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on EnrolRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EnrolRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EnrolRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EnrolRequestMultiError, or
// nil if none found.
func (m *EnrolRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *EnrolRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EnrolToken

	// no validation rules for Csr

	// no validation rules for AccessHandlerUrl

	switch m.Proof.(type) {

	case *EnrolRequest_Aws:

		if all {
			switch v := interface{}(m.GetAws()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, EnrolRequestValidationError{
						field:  "Aws",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, EnrolRequestValidationError{
						field:  "Aws",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetAws()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return EnrolRequestValidationError{
					field:  "Aws",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return EnrolRequestMultiError(errors)
	}
	return nil
}

// EnrolRequestMultiError is an error wrapping multiple validation errors
// returned by EnrolRequest.ValidateAll() if the designated constraints aren't met.
type EnrolRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EnrolRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EnrolRequestMultiError) AllErrors() []error { return m }

// EnrolRequestValidationError is the validation error returned by
// EnrolRequest.Validate if the designated constraints aren't met.
type EnrolRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EnrolRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EnrolRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EnrolRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EnrolRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EnrolRequestValidationError) ErrorName() string { return "EnrolRequestValidationError" }

// Error satisfies the builtin error interface
func (e EnrolRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEnrolRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EnrolRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EnrolRequestValidationError{}

// Validate checks the field values on EnrolResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EnrolResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EnrolResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EnrolResponseMultiError, or
// nil if none found.
func (m *EnrolResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *EnrolResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return EnrolResponseMultiError(errors)
	}
	return nil
}

// EnrolResponseMultiError is an error wrapping multiple validation errors
// returned by EnrolResponse.ValidateAll() if the designated constraints
// aren't met.
type EnrolResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EnrolResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EnrolResponseMultiError) AllErrors() []error { return m }

// EnrolResponseValidationError is the validation error returned by
// EnrolResponse.Validate if the designated constraints aren't met.
type EnrolResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EnrolResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EnrolResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EnrolResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EnrolResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EnrolResponseValidationError) ErrorName() string { return "EnrolResponseValidationError" }

// Error satisfies the builtin error interface
func (e EnrolResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEnrolResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EnrolResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EnrolResponseValidationError{}

// Validate checks the field values on AWSProof with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AWSProof) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AWSProof with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AWSProofMultiError, or nil
// if none found.
func (m *AWSProof) ValidateAll() error {
	return m.validate(true)
}

func (m *AWSProof) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetIdentity()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AWSProofValidationError{
					field:  "Identity",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AWSProofValidationError{
					field:  "Identity",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetIdentity()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AWSProofValidationError{
				field:  "Identity",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetOrganization()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AWSProofValidationError{
					field:  "Organization",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AWSProofValidationError{
					field:  "Organization",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOrganization()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AWSProofValidationError{
				field:  "Organization",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AWSProofMultiError(errors)
	}
	return nil
}

// AWSProofMultiError is an error wrapping multiple validation errors returned
// by AWSProof.ValidateAll() if the designated constraints aren't met.
type AWSProofMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AWSProofMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AWSProofMultiError) AllErrors() []error { return m }

// AWSProofValidationError is the validation error returned by
// AWSProof.Validate if the designated constraints aren't met.
type AWSProofValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AWSProofValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AWSProofValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AWSProofValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AWSProofValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AWSProofValidationError) ErrorName() string { return "AWSProofValidationError" }

// Error satisfies the builtin error interface
func (e AWSProofValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAWSProof.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AWSProofValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AWSProofValidationError{}

// Validate checks the field values on AWSSignature with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AWSSignature) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AWSSignature with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AWSSignatureMultiError, or
// nil if none found.
func (m *AWSSignature) ValidateAll() error {
	return m.validate(true)
}

func (m *AWSSignature) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Signature

	if all {
		switch v := interface{}(m.GetTimestamp()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AWSSignatureValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AWSSignatureValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTimestamp()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AWSSignatureValidationError{
				field:  "Timestamp",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for SecurityToken

	if len(errors) > 0 {
		return AWSSignatureMultiError(errors)
	}
	return nil
}

// AWSSignatureMultiError is an error wrapping multiple validation errors
// returned by AWSSignature.ValidateAll() if the designated constraints aren't met.
type AWSSignatureMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AWSSignatureMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AWSSignatureMultiError) AllErrors() []error { return m }

// AWSSignatureValidationError is the validation error returned by
// AWSSignature.Validate if the designated constraints aren't met.
type AWSSignatureValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AWSSignatureValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AWSSignatureValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AWSSignatureValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AWSSignatureValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AWSSignatureValidationError) ErrorName() string { return "AWSSignatureValidationError" }

// Error satisfies the builtin error interface
func (e AWSSignatureValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAWSSignature.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AWSSignatureValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AWSSignatureValidationError{}

// Validate checks the field values on GetCertificateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCertificateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCertificateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCertificateRequestMultiError, or nil if none found.
func (m *GetCertificateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCertificateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Csr

	// no validation rules for Tenant

	// no validation rules for Provider

	switch m.Proof.(type) {

	case *GetCertificateRequest_Aws:

		if all {
			switch v := interface{}(m.GetAws()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetCertificateRequestValidationError{
						field:  "Aws",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetCertificateRequestValidationError{
						field:  "Aws",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetAws()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetCertificateRequestValidationError{
					field:  "Aws",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetCertificateRequestMultiError(errors)
	}
	return nil
}

// GetCertificateRequestMultiError is an error wrapping multiple validation
// errors returned by GetCertificateRequest.ValidateAll() if the designated
// constraints aren't met.
type GetCertificateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCertificateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCertificateRequestMultiError) AllErrors() []error { return m }

// GetCertificateRequestValidationError is the validation error returned by
// GetCertificateRequest.Validate if the designated constraints aren't met.
type GetCertificateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCertificateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCertificateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCertificateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCertificateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCertificateRequestValidationError) ErrorName() string {
	return "GetCertificateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetCertificateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCertificateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCertificateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCertificateRequestValidationError{}

// Validate checks the field values on GetCertificateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCertificateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCertificateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCertificateResponseMultiError, or nil if none found.
func (m *GetCertificateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCertificateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Certificate

	if len(errors) > 0 {
		return GetCertificateResponseMultiError(errors)
	}
	return nil
}

// GetCertificateResponseMultiError is an error wrapping multiple validation
// errors returned by GetCertificateResponse.ValidateAll() if the designated
// constraints aren't met.
type GetCertificateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCertificateResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCertificateResponseMultiError) AllErrors() []error { return m }

// GetCertificateResponseValidationError is the validation error returned by
// GetCertificateResponse.Validate if the designated constraints aren't met.
type GetCertificateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCertificateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCertificateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCertificateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCertificateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCertificateResponseValidationError) ErrorName() string {
	return "GetCertificateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetCertificateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCertificateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCertificateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCertificateResponseValidationError{}
